# For more info on HTTP files go to https://aka.ms/vs/httpfile
@BookMatrix.API_HostAddress = https://localhost:7063

Post {{BookMatrix.API_HostAddress}}/Account/Login
Accept: application/json
content-type : application/json
{
  "username":"sj@gmail.com",
  "password":"Jssj@12345678"
}
###
